[package]
name = "rmcp-axum"
version.workspace = true
edition.workspace = true
description = "Collection of tower extensions for serve `rmcp` with `axum`."

[dependencies]
axum = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
tower = { workspace = true }
