[package]
name = "rmcp-axum"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
tower = { workspace = true }
